version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 25
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 15
  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 15    
  
            
workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - one
      - two:
          requires:
            - one
      - hold:
          type: approval
          requires:
           - one
     - deploy:
          requires:
            - hold
