# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 379b81bb0f8ac4b67ce1083992aa7f4da079e6206877070b045a525e8486a3d191022f3ed9ae2c8e6495be77f98b96d5c8afd0733811d99f7952906da52c91c5

test:
  secret_key_base: 4aadedc7be0b99c686dd28d8ad50177e28910a8410d376e5c1066576caa9fcd204771277bcb51906bf50ad3a1295bcdfc62930bce8963a6da70aae94d4a6caea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
